### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by Rich-Harris** [Rich-Harris/packd#10]
this should probably be behind Cloudflare or something

**Comment by xtuc** [comment]
Do you want to stick with now.sh? Do you actually pay for it?

I'm fine with setting up the stack in AWS, what do you think?

**Comment by Rich-Harris** [comment]
Devops stuff really isn't my forte and now is an insanely convenient and easy-to-use service, so I probably will keep packd.now.sh going. I do pay for it — $15/mo — but that includes a bunch of other websites as well, not just packd.

But I'm strongly in favour of having other instances running elsewhere as well! Would be amazing to see this running on AWS, set up for a real production workload 😀

**Comment by xtuc** [comment]
Ok, it's up and running. I also found a good name: [bundle.run](https://bundle.run).

I had to make a few fixes to be able to run it on AWS, https://github.com/Rich-Harris/packd/pull/16.

**Comment by xtuc** [comment]
I would like to disable packd's internal cache because the CDN will cache it anyway. This will also decrease the memory usage on the server.

Would you be open to add an option to disable the behavior?

**Comment by Rich-Harris** [comment]
Yep, that makes sense. I'm just in the process of rewriting some code around that (so that bundling and minification happens in a child process), so probably best to hold off just for the moment — I should be out of the way fairly soon though!

**Comment by xtuc** [comment]
Can we close this?

**Comment by Rich-Harris** [comment]
Yep — have updated the README with links to bundle.run
