### ISSUE TITLE
Bundle.run appears to be down/ malfunctioning 

### ISSUE THREAD

**Issue by jparklev** [Rich-Harris/packd#113]
Packages that were working yesterday are erring out today. For example, when I hit `https://bundle.run/left-pad@1.3.0`, I see 
<img width="1300" alt="Screen Shot 2020-04-15 at 2 36 48 AM" src="https://user-images.githubusercontent.com/24902242/79305826-176d0f80-7ec2-11ea-97b9-56fb0b73e268.png">

**Comment by j-f1** [comment]
Seems fine for me

**Comment by xtuc** [comment]
Seems fine to me. In what region are you?

**Comment by jparklev** [comment]
I'm around NYC. Still seems there are packages that were working 2 days ago but not today. https://bundle.run/theme-ui gets `Gateway time-out` for me now
