### ISSUE TITLE
bundle.run returns server error

### ISSUE THREAD

**Issue by oluckyman** [Rich-Harris/packd#114]
That url worked for me before:
![image](https://user-images.githubusercontent.com/642673/79431967-779ba880-7fcb-11ea-8bc8-387763523cc7.png)
```
ENOENT: no such file or directory, open '/var/app/current/.tmp/88f591a13f2c9d15f254a37d13751845afb0b290/package/lib/index.js.js'
```

Tried the latest version:
![image](https://user-images.githubusercontent.com/642673/79431932-69e62300-7fcb-11ea-8229-6ba473418798.png)

I'm in Spain

**Comment by xtuc** [comment]
I invalidated the cache and it's working now
