### ISSUE TITLE
ENOSPC: no space left on device

### ISSUE THREAD

**Issue by wizzard0** [Rich-Harris/packd#120]
URL: `https://bundle.run/@azure/cosmos@3.6.3`

Error:
ENOSPC: no space left on device, mkdir '/tmp/d211428224dea8fc126e1be5fc43823f0c298fd6'

**Comment by xtuc** [comment]
Should be fixed, sorry about that

**Comment by wizzard0** [comment]
Thanks! Though that particular module doesn't look good, I'm pretty sure there's a lot of code there :)

**Comment by xtuc** [comment]
the package has multiple entrypoint, you can try to target the file you are interested in using `https://bundle.run/@azure/cosmos@3.6.3/somefile.js`
