### ISSUE TITLE
https://bundle.run/line-clamp@1.0.0 - server error

### ISSUE THREAD

**Issue by augustolima** [Rich-Harris/packd#121]
Hello, I'm facing this issue. What can I do to help?

https://bundle.run/line-clamp@1.0.0

Command failed: npm_config_cache=/tmp /app/node_modules/.bin/npm install --production npm WARN locking Error: ENOSPC: no space left on device, open '/tmp/_locks/staging-7ec325dfa35eaf69.lock' npm WARN locking /tmp/_locks/staging-7ec325dfa35eaf69.lock failed { [Error: ENOSPC: no space left on device, open '/tmp/_locks/staging-7ec325dfa35eaf69.lock'] npm WARN locking stack: npm WARN locking 'Error: ENOSPC: no space left on device, open \'/tmp/_locks/staging-7ec325dfa35eaf69.lock\'', npm WARN locking errno: -28, npm WARN locking code: 'ENOSPC', npm WARN locking syscall: 'open', npm WARN locking path: '/tmp/_locks/staging-7ec325dfa35eaf69.lock' } npm ERR! code ENOSPC npm ERR! syscall open npm ERR! path /tmp/_locks/staging-7ec325dfa35eaf69.lock npm ERR! errno -28 npm ERR! nospc ENOSPC: no space left on device, open '/tmp/_locks/staging-7ec325dfa35eaf69.lock' npm ERR! nospc There appears to be insufficient space on your system to finish. npm ERR! nospc Clear up some disk space and try again.

**Comment by xtuc** [comment]
disk are filling up more than I expected. I will fix

**Comment by xtuc** [comment]
The service is working now. I see that your packages throws `package has no entry file; please specify a `module` key in your `package.json`.`
