### ISSUE TITLE
ENOSPC: no space left on device

### ISSUE THREAD

**Issue by tchetwin** [Rich-Harris/packd#123]
For [this URL](https://bundle.run/@babel/plugin-proposal-numeric-separator@7.10.1):

> ### server error
> Please raise an issue, quoting this URL.
> `ENOSPC: no space left on device, mkdir '/tmp/99c61a5bf2815ecf460cdae465b19b930de47e33'`

Similar to #120 and #121. @xtuc fixed both of those previous Issues.

**Comment by xtuc** [comment]
Sorry about that. I cleaned the instances.

**Comment by tchetwin** [comment]
No worries, thanks!
