### ISSUE TITLE
Update to ZEIT Now 2, Vercel [[Deadline: August 7th]]

### ISSUE THREAD

**Issue by fregante** [Rich-Harris/packd#129]
ZEIT Now 1 will be phased out in less than a month and I don't see any mention of this deadline in the repo.

**packd will stop working on August 7th**

- Official announcement: https://mailchi.mp/f923e55efe1d/simplified-pricing-1087517
- Possible fix: https://stackoverflow.com/a/62453071

**Comment by fregante** [comment]
I tested my fork of packd and almost managed to make it run: https://github.com/fregante/packd/pull/2

The problem is that now there's a hard duration limit of 10 seconds for the "hobby" account: https://vercel.com/docs/v2/platform/limits

This severely limits the feasibility of packd on Vercel:

```
[GET] /doma@3.0.1
18:02:10:16
packd info [doma] requested package
packd info [doma] is not cached
packd info /var/task/server
packd info /var/task/server/child-processes/create-bundle.js
/var/task
packd info [doma] fetching https://registry.npmjs.org/doma/-/doma-3.0.1.tgz
packd info [doma] extracting to /tmp/f128ef27-dcfb-49cb-9cca-3b4707fccbba/90c0e61c9df54f74f16f5d94831cf4eaa5a6c1df/package
packd info [doma] running  npm install --production
2020-08-02T17:02:20.584Z c664180e-a69e-4760-9d6a-f2c1394e59e0 Task timed out after 10.01 seconds
```

**Comment by fregante** [comment]
Packd is officially offline:

<img width="667" alt="Screen Shot 2020-09-21 at 01 38 46" src="https://user-images.githubusercontent.com/1402241/93738373-3b3c2c00-fbab-11ea-805e-6463b630d685.png">


bundle.run however seems to continue working. Perhaps it should just drop the Vercel integration/mention.

**Comment by xtuc** [comment]
bundle.run isn't hosted on Vercel and not planning to taking it down
