### ISSUE TITLE
ENOSPC: no space left on device

### ISSUE THREAD

**Issue by abitrolly** [Rich-Harris/packd#136]
https://bundle.run/ansi-to-html@0.6.14
```
ENOSPC: no space left on device, mkdir '/tmp/c967dafc1be731bbe639f98f350c6ee01466938d'
```
![image](https://user-images.githubusercontent.com/8781107/91310770-f515c780-e7ba-11ea-8819-eba7a77f039f.png)

**Comment by xtuc** [comment]
fixed

**Comment by abitrolly** [comment]
@xtuc thanks, Sven.
