### ISSUE TITLE
"ENOSPC: no space left on device" when loading a library

### ISSUE THREAD

**Issue by quentin-sommer** [Rich-Harris/packd#138]
Saw this error for this url: https://bundle.run/dagre-d3@0.6.4
```
ENOSPC: no space left on device, mkdir '/tmp/d01a4f5c0cfed51420b1049c510b90ebda3b809c'
```
![Screenshot from 2020-08-29 15-09-24](https://user-images.githubusercontent.com/9129496/91637573-c3467000-ea09-11ea-822b-a5e5493924bc.png)

**Comment by xtuc** [comment]
fixed

**Comment by quentin-sommer** [comment]
Thanks :slightly_smiling_face:
