### ISSUE TITLE
Server error for normalize.css

### ISSUE THREAD

**Issue by tomgreenhill** [Rich-Harris/packd#139]
As requested here's an issue raise for an error found.

`Unexpected token`

URL error found: https://bundle.run/normalize.css@8.0.1

Thanks,
Tom

**Comment by fregante** [comment]
normalize.css is not a script. Use cdnjs instead.

**Comment by tomgreenhill** [comment]
I’m aware it’s not a script, but it’s listed as somewhere to use/pull normalize from. Requests you post so I did. I’ve not used bundle.run before, sorry.
