### ISSUE TITLE
Unexpected character '@'

### ISSUE THREAD

**Issue by ghost** [Rich-Harris/packd#142]
![Screenshot (97)](https://user-images.githubusercontent.com/76587897/105839310-4db1f080-5ff7-11eb-9e77-9e4dea7b5254.png)
https://bundle.run/reseter.css@1.0.2

**Comment by j-f1** [comment]
It looks like that file is a CSS file, not a JavaScript file. Since `bundle.run` interprets the main file as JS, you should use something like unpkg (https://unpkg.com/reseter.css@1.0.2/css/reseter.min.css) to get the plain-text version of the CSS file.

**Comment by ghost** [comment]
Thanks @j-f1
