### ISSUE TITLE
Non-minified result

### ISSUE THREAD

**Issue by tunnckoCore** [Rich-Harris/packd#15]
Heya.

Just playing here with some thing, so want to ask something and it will be probably reporting a bug. Just tried https://packd.now.sh/preact and it results in non-minified UMD, is it expected or? Most of other packages are UMD-ified and minified, and i think "always minified" is a part of the purpose of packd.

Looked what Preact does and it expose `jsnext:main` bundle non minified, and `main` cjs non-minified. When another package is exposed (https://packd.now.sh/dush for example) with same strategy packd returns UMD+minified result, which is expected.

**Comment by Rich-Harris** [comment]
Preact uses ES6 features that Uglify (at least, the version packd uses) can't minify. If a package fails to minify, packd serves an unminified version instead.

Am planning to fix this with https://butternut.now.sh, once I iron out a few bugs. Will close this as it's 'expected' behaviour even if it's incorrect

**Comment by tunnckoCore** [comment]
Oh yea, i just was reading the code, but just stopped exactly before that case :D :D 

No problem.

**Comment by eight04** [comment]
Is there an option to tell the server to serve the non-minified version?
