### ISSUE TITLE
How to use https://bundle.run/promisify-child-process@4.1.1

### ISSUE THREAD

**Issue by Kali95739** [Rich-Harris/packd#162]
Example ? @xtuc @Rich-Harris

**Comment by Rich-Harris** [comment]
you can't, it depends on `child_process` which is a node module. i've no idea what you're trying to do, but bundle.run is the wrong tool to do it with — it's a way of serving packages to the browser

**Comment by Kali95739** [comment]
So u are saying u cant use any node module? For example fs or net or just child_process

**Comment by Rich-Harris** [comment]
yes

**Comment by Kali95739** [comment]
Ah okay thanks
