### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by lukeed** [Rich-Harris/packd#32]
Hey Rich,

I'm serving `tinydate` via Packd to a JSFiddle. It was pointed out to me that the fiddle was broken. Seems like the Packd link is not working.

The original link is: `https://packd.now.sh/tinydate@1.0.0`

Which gets sent thru to: `https://zeit.co/rich_harris/packd/ttpgkdtmfp?redirect=1`, which halts there with a 403 forbidden.

Thanks!

**Comment by xtuc** [comment]
Ouch, it seems that Rich's service is down.

You can meanwhile use the CDN one https://bundle.run/tinydate@1.0.0.

**Comment by lukeed** [comment]
Thanks Sven, didn't know about that one.

**Comment by xtuc** [comment]
I just found this issue again and noticed that packd.now.sh is still down. Did bundle.run fix your issue @lukeed?
