### ISSUE TITLE
Use Babili?

### ISSUE THREAD

**Issue by Rich-Harris** [Rich-Harris/packd#4]
Some packages can't be minified with Uglify, e.g. [Preact](https://packd.now.sh/bundle/preact@7.2.1), due to their use of ES2015 that Uglify doesn't support. While I don't think we should *default* to Babili, maybe we could fall back to it.

**Comment by monfera** [comment]
May be related: I just tried https://github.com/monfera/crosslink - which uses `rollup` - with the awesome `packd` and it indeed didn't minify (it minifies locally with the devDependency `rollup-plugin-babili` when doing an `npm build`).

**Comment by Rich-Harris** [comment]
Unfortunately Babili is a bit too slow to be used in this context, so I'm working on an alternative: https://butternut.now.sh/?version=0.4.3&gist=23e0931a09f412fd26c8bf7a3b85da05

There's also [uglify-es](npmjs.com/package/uglify-es) which was released the other day — is basically the 'harmony' branch of the Uglify project

**Comment by monfera** [comment]
Wow, thanks for the pointer! Also, here's wishing that the Google Closure devs will eventually support ES2015 as an optional output as it can be quite compact.

**Comment by j-f1** [comment]
There have been a couple PRs recently to babel-minify (the new name for babili), and it should be getting quite a bit faster soon.

**Comment by xtuc** [comment]
Closing since https://github.com/Rich-Harris/packd/pull/65#issuecomment-455562126
