### ISSUE TITLE
CDN and demo instances are running different versions

### ISSUE THREAD

**Issue by nickmccurdy** [Rich-Harris/packd#40]
I noticed that https://bundle.run/ is on `2.5.2` but https://packd.now.sh/ is on `2.6.1`. Is this intentional or should a cahe invalidation or deploy occur on `bundle.run`? Also the repository's URL on GitHub (not in the readme) is https://packd.now.sh, I would expect it to be https://bundle.run/ because I was initially confused about which one was preferable until I read the readme.

**Comment by xtuc** [comment]
bundle.run is deployed for each new git tag, currently the latest (2.6.1) is running, but the version in the package.json is not up-to-date. Rich fixed it in https://github.com/Rich-Harris/packd/commit/c3ce936b15486c6f89e32dfa77f4617074f6b059, I'll make a tag to deploy the new version.

I thought @Rich-Harris had shut down the now instance? As said in the README it's recommended to use the CDN version.

**Comment by nickmccurdy** [comment]
Thank you, I'm now under the impression that https://bundle.run/ is the way to go. Seems like the repository URL should be changed.

By the way, you can use `npm version` to automatically increment your package version in `package.json`, and it additionally tags the version for you. Then all you have to do is `npm publish`, `git push`, and `git push --tags`.

**Comment by xtuc** [comment]
https://bundle.run has been updated.

> Seems like the repository URL should be changed.

"bundle.run" is not the initial author, let's see what @Rich-Harris thinks about that.

**Comment by nickmccurdy** [comment]
Thanks for the quick resolution!

Quick question: I'm working on a tool for CDN users to help them update dependencies similar to `npm update` (https://github.com/nickmccurdy/cdnm), and I thought it would be a good idea to support packd after seeing a link to https://bundle.run/  on https://yarnpkg.com/. Should I just support the https://bundle.run/ since it's the production CDN, or both in case a page has links to https://packd.now.sh/?

**Comment by xtuc** [comment]
Yes, `bundle.run` is the production platform for packd.

According to the README:
```
bundle.run — CDN
packd.now.sh — demo instance
```
