### ISSUE TITLE
Server Error when installing `styled-components`

### ISSUE THREAD

**Issue by jgierer12** [Rich-Harris/packd#43]
https://bundle.run/styled-components@3.2.1?name=__npm_module_1

```
Command failed: /var/app/current/node_modules/.bin/npm install react@>= 0.14.0 < 17.0.0-0 /bin/sh: 17.0.0-0: No such file or directory 
```

**Comment by xtuc** [comment]
Thanks for the report.

It seems that I have a similar warning locally `npm WARN styled-components@3.2.1 requires a peer of react@>= 0.14.0 < 17.0.0-0 but none is installed. You must install peer dependencies yourself.`, but i'm still able to install it.

I'm not sure why this is happening yet, i'm working on it.

**Comment by xtuc** [comment]
Ok it's live: https://bundle.run/styled-components@3.2.1.
