### ISSUE TITLE
Server error for regl-camera

### ISSUE THREAD

**Issue by mootari** [Rich-Harris/packd#49]
URL: https://bundle.run/regl-camera@2.1.1
Error:

    ENOENT: no such file or directory, stat '/var/app/current/.tmp/2623c0b9d4d77b74809816caf99130166322fc1b/package.tgz'

I can confirm that the URL was working approx. 10 days ago.

**Comment by xtuc** [comment]
It's working on my side. I invalided the URL in the CDN, could you please retry?

**Comment by mootari** [comment]
Yup, it's working again. Thanks!
