### ISSUE TITLE
hapi and typescript fail

### ISSUE THREAD

**Issue by Rich-Harris** [Rich-Harris/packd#5]
Couple more failures found via the logs:

* https://packd.now.sh/bundle/hapi@16.1.0
* https://packd.now.sh/bundle/typescript@2.2.2
* https://packd.now.sh/bundle/preact-compat@3.14.3
* https://packd.now.sh/bundle/charts@0.0.3

Don't know the cause yet

**Comment by xtuc** [comment]
Only charts is failing now, and it's for C++ dependecies that fail to compile. I would suggest closing this issue.
