### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by joshuahhh** [Rich-Harris/packd#53]
https://bundle.run/polybooljs@1.2.0 tells me:
```
ENOENT: no such file or directory, stat '/var/app/current/.tmp/19a697fc7152c4b489dbb0e87ca3761dc47084f5/package.tgz'
```

(Even though it worked four days ago.)

Looks a lot like #51, #49, etc.

**Comment by joshuahhh** [comment]
https://packd.now.sh/polybooljs@1.2.0 works, so I imagine this is some transient error cached by a CDN?

**Comment by xtuc** [comment]
Thanks for the report. I've invalidated the entry, could you please confirm that it's working on your side now?

**Comment by joshuahhh** [comment]
Looks like it's fixed now. Thanks a bunch. 😄

(I really appreciate your dealing with these issues. I am also curious to know whether the underlying problem has been identified yet.)

**Comment by xtuc** [comment]
I just invalidated the URL in AWS CloudFront (the cdn used by bundle.run). I don't know what the underlying was, maybe a broken version on npm or a failure on a node.

**Comment by joshuahhh** [comment]
OK now I ran into trouble with two more libraries:

https://bundle.run/earcut@2.1.3
```
ENOENT: no such file or directory, stat '/var/app/current/.tmp/7623c50f6531d0eefc9c4dd33db3ac420b52ebd9/package.tgz'
```

https://bundle.run/json-stringify-pretty-compact@1.2.0
```
Command failed: npm_config_cache=~/.npm /var/app/current/node_modules/.bin/npm install --production path.js:1163 cwd = process.cwd(); ^ Error: ENOENT: no such file or directory, uv_cwd at Object.resolve (path.js:1163:25) at Function.Module._resolveLookupPaths (module.js:408:17) at Function.Module._resolveFilename (module.js:480:22) at Function.Module._load (module.js:437:25) at Module.require (module.js:513:17) at require (internal/module.js:11:18) at /var/app/current/node_modules/npm/bin/npm-cli.js:19:21 at Object. (/var/app/current/node_modules/npm/bin/npm-cli.js:143:3) at Module._compile (module.js:569:30) at Object.Module._extensions..js (module.js:580:10)
```

Both worked in the past. Both work now using https://packd.now.sh/. Am I doing something wrong, to run into all these problems? 😛 (In case it's a clue, I'm accessing these from an https://observablehq.com/ notebook, since I was pointed here from https://beta.observablehq.com/@tmcw/requiring-modules-troubleshooting.)

**Comment by xtuc** [comment]
Interesting, on my side, I don't see this issue, maybe it's only on the first download from npm.

I'm going to invalid these entries and try to investigate the root issue. Also in other region of the CDN it works and there isn't any logic in the CDN itself so i'm not sure yet.

**Comment by shaunlebron** [comment]
The following URLs used to work, but seem to be down:

- https://bundle.run/lru-cache@4.1.3
- https://bundle.run/bintrees@1.0.2
- https://bundle.run/linear-solve@1.2.1
- https://bundle.run/lodash.debounce@4.0.8

Here are the errors I'm seeing for each:

```

ENOENT: no such file or directory, stat '/var/app/current/.tmp/051fea07f12ec90937c13b26005820b8074104d6/package.tgz'
```

**Comment by xtuc** [comment]
I think that this issue is resolved, some things were changed since it. Feel free to re-open it if needed.
