### ISSUE TITLE
Server error on https://bundle.run/h3-js

### ISSUE THREAD

**Issue by nrabinowitz** [Rich-Harris/packd#55]
Server error on https://bundle.run/h3-js@3.0.2
```
ENOENT: no such file or directory, open '/var/app/current/.tmp/04441de3649b5f2fdd9c7ba6464c328a9cef8a7a/package/index.js.js'
```
The latest version https://bundle.run/h3-js@3.1.0 works, but https://bundle.run/h3-js resolves to 3.0.2.

**Comment by xtuc** [comment]
I invalided the entry, could you please try again? I'm not able to reproduce the issue, but that might be because I'm in another region.
