### ISSUE TITLE
Server Error: No such file or directory

### ISSUE THREAD

**Issue by void4** [Rich-Harris/packd#56]
When trying to build
https://bundle.run/webassemblyjs
this happens:
```
: ENOENT: no such file or directory, open '/var/app/current/.tmp/12d8f69da88004cfb0ec68f4df89c40012a5b8fc/package/esm/index.js.js'
```

**Comment by xtuc** [comment]
I invalidated the entry and now the error changed: building ESM seems broken, I would recommend you to use https://bundle.run/webassemblyjs@1.7.4/lib/index.js instead.
