### ISSUE TITLE
(cached) server error on keyword-extractor@0.0.15

### ISSUE THREAD

**Issue by tpreusse** [Rich-Harris/packd#62]
Used to work. Broke my observablehq notebook. Tmp build error that is now cached?

https://bundle.run/keyword-extractor@0.0.15 (used to work)
<img width="817" alt="screen shot 2018-11-22 at 15 27 31" src="https://user-images.githubusercontent.com/410211/48908622-271e2b00-ee6b-11e8-887c-b0e85bbb5df9.png">

https://bundle.run/keyword-extractor@0.0.14 (works)

I'm located in Zürich (maybe only on region cache is broken)

**Comment by xtuc** [comment]
I invalidated it yesterday, sorry I was on a train, could you please try again?

**Comment by tpreusse** [comment]
works, thank you
