### ISSUE TITLE
Can't load babel-plugin-styled-components

### ISSUE THREAD

**Issue by liamness** [Rich-Harris/packd#69]
https://bundle.run/babel-plugin-styled-components@1.10.0

Error is `ENOENT: no such file or directory, open '/var/app/current/.tmp/5e3d0376ee07f7ee82fade73933be9e40942eb0b/package/lib/index.js.js'`

Came across this when trying to play around with styled components on the [Babel REPL](https://babeljs.io/repl), which uses packd to load more esoteric plugins.

**Comment by xtuc** [comment]
It's loading fine on my side, I'm invalidating the entry in the CDN.

**Comment by xtuc** [comment]
Has been invalidated, could you please confirm it works on your side?

**Comment by liamness** [comment]
Yeah, it's working fine now thanks!
