### ISSUE TITLE
https://bundle.run/yuml-diagram@1.0.10

### ISSUE THREAD

**Issue by ehouais** [Rich-Harris/packd#80]
ENOENT: no such file or directory, lstat '/var/app/current/.tmp/790498ba135e8a384de02b3691fb70f6f7d20656/package/node_modules/ajv/lib/refs'

**Comment by xtuc** [comment]
I invalided the entry, could you please confirm it's working again?

**Comment by ehouais** [comment]
Don't know what you mean by 'I invalidated the entry', but it's working again indeed :) Thx
