### ISSUE TITLE
Error ENOENT for package bresenham

### ISSUE THREAD

**Issue by mootari** [Rich-Harris/packd#81]
- URL: https://bundle.run/bresenham@0.0.4
- Error: ```ENOENT: no such file or directory, open '/var/app/current/.tmp/e2b6abaa1248eb808cc18725c8bc97cca17b0733/package/index.js.js'```

Response headers:
```
age: 253
content-length: 962
date: Thu, 30 May 2019 18:22:42 GMT
server: nginx/1.12.1
status: 200
via: 1.1 ffa01f5c992a803f4470401daea2d541.cloudfront.net (CloudFront)
x-amz-cf-id: yUV0QY07-lojjGM7gxqFUCzBErCpEdP4GHVmwUQjvxazFoe0NRsrwg==
x-cache: Hit from cloudfront
x-powered-by: Express
```

**Comment by PlNG** [comment]
Have you tried again? I get a response.

**Comment by mootari** [comment]
Yep, it's working now.
