### ISSUE TITLE
https://bundle.run/pixi-tiled-utils@1.0.7?name=__npm_module_1 doenst work

### ISSUE THREAD

**Issue by Prozi** [Rich-Harris/packd#82]
IDK why

**Comment by Prozi** [comment]
Appending ?name=__npm_module_1 makes this bug appear

without it works

**Comment by Prozi** [comment]
@Rich-Harris cc

**Comment by j-f1** [comment]
What do you mean by “doesn’t work?”

**Comment by Prozi** [comment]
ENOENT: no such file or directory, open '/var/app/current/.tmp/...

**Comment by Prozi** [comment]
Just open the link

**Comment by j-f1** [comment]
It opens fine for me. Try Ctrl+Shift+R to force your browser to redownload it maybe?

**Comment by Prozi** [comment]
Resolved
