### ISSUE TITLE
several babel packages not loading

### ISSUE THREAD

**Issue by hellatan** [Rich-Harris/packd#95]
it seems like the following babel plugins are not loading:

- `@babel/plugin-transform-flow-strip-types@7.7.4`
- `babel-plugin-transform-react-remove-prop-types@0.4.24`

both return some form of 
```
ENOENT: no such file or directory, open '/var/app/current/.tmp/9a3a73cd56318fc3798c479a27dc7d6c60307824/package/lib/index.js.js'
```
where the hash is just a different value.

https://bundle.run/babel-plugin-transform-react-remove-prop-types@0.4.24
https://bundle.run/@babel/plugin-transform-flow-strip-types@7.7.4

I'm trying to load all of these from https://babeljs.io/en/repl.

**Comment by xtuc** [comment]
Hi, I restarted the backend server a few minuites ago and this might be unlucky timing. Could you please check if it's working again?

**Comment by hellatan** [comment]
it seems like it's still caching somewhere. when I try one of the links above, it's still erroring out. If i add a random query parameter to it, it loads fine.

**Comment by hellatan** [comment]
https://bundle.run/@babel/plugin-transform-flow-strip-types@7.7.4 (still errors)

vs

https://bundle.run/@babel/plugin-transform-flow-strip-types@7.7.4?asdf (loads...eventually)

**Comment by xtuc** [comment]
Good point. I purge both these URLs. Closing for now, please let me know if that doesn't work for you.

**Comment by hellatan** [comment]
great, seems to be fixed now. thanks!
