### ISSUE TITLE
https://bundle.run/bn.js@5.0.0

### ISSUE THREAD

**Issue by ctzurcanu** [Rich-Harris/packd#98]
"ENOENT: no such file or directory, open '/var/app/current/.tmp/6daf8010aae4306bba7e70bc3a68394180c9b56f/package/lib/bn.js.js'"

**Comment by xtuc** [comment]
Invalidated cache for https://bundle.run/bn.js@5.0.0. Please let me know if it doesn't work for you.

**Comment by ctzurcanu** [comment]
yes. i had to reset the cache too. thank you for answering so fast!
